batch_size: 20
data:
  img_size: [1, 2, 4, 8, 16, 32, 64, 128]
  is_noise: false
  noise_num: ''
  object_array:
  - 1
  - 2
  - 4
  - 8
  - 16
  - 32
  - 64
  - 128
  path: ''
defaults:
- override hydra/sweeper: optuna
- override hydra/sweeper/sampler: tpe
epoch: 500
hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: minimize
    n_trials: 500
    params:
      data.object_array: choice([1],[2],[4],[8],[16],[32],[64],[128],[1, 2, 4, 8, 16, 32, 64, 128])
      model.k: range(10, 100, step=1)
      optimizer.lr: range(0.0001, 0.01, step=0.0001)
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 93
    study_name: sphere
loss: CrossEntropy
dendrite: 1
init_q: -0.5
init_w_add: -0.2
init_w_mul: 1e-10
k: 10
name: Dmodel
optimizer:
  lr: 3e-4
  name: Adam
  weight_decay: 1.0e-06
scheduler:
  T_max: 1000
  eta_min: 1.0e-06
  name: CosineAnnealingLR
seed: 38
wandb:
  entity: ruriiiii
  experiment_name: ''
  group_name: ini1
  is_save_code: false
  is_sweep: false
  project_name: GSOOorientation-detection
