program: src/train.py
method: grid

metric:
  goal: minimize
  name: test_loss

entity: "kanazawa-nougata-lab"
project: "Dmodel-sweep-CNN-object"

parameters:
  model:
    values: ["Dmodel"] # , "TwoChCNN", "TwoChFCCNN", "OneChFCCNN"] # ["Dmodel","OneChCNN","OneChFCCNN", "TwoChCNN", "TwoChFCCNN" ]
  data.object_array:
    values:
      [
        [1],
        [2],
        [4],
        [8],
        [16],
        [32],
        [64],
        [128],
        [256],
      ]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
